version: 0.0
os: linux
files:
- source: /target/helloworld.war
  destination: /usr/share/tomcat/webapps/
# - source: /scripts/requirements.txt
#   destination: /home/ec2-user/scripts
hooks:
  BeforeInstall:
  - location: scripts/clean_war
    timeout: 300
    runas: root
  - location: scripts/restart
    timeout: 300
    runas: root
  AfterInstall:
  - location: scripts/restart
    timeout: 300
    runas: root
#   - location: s
